### ISSUE TITLE
Articulated Robots in Hab3.0 for ObjectNav benchmark

### ISSUE THREAD

**Issue by wzcai99** [facebookresearch/habitat-lab#1646]
How to configure different articulated agents for the object-navigation benchmark? Since in the hab3.0, I noticed that there are different config files for articulated agents, and if I want to make a spot-objectnav task, can I directly copy the dict values in "config/habitat/simulators/agents/spot.yaml" to replace the benchmark objectnav main agent values like this:
```
# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_head_rgbd_arm_agent
  - /habitat/dataset/objectnav: hm3d
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    turn_angle: 30
    debug_render_articulated_agent: True
    agents:
      main_agent:
        radius: 0.25
        height: 1.41
        articulated_agent_type: "SpotRobot"
        articulated_agent_urdf: data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf
        sim_sensors:
          arm_rgb_sensor:
            height: 480
            width: 640
            hfov: 47
          arm_depth_sensor:
            height: 224
            width: 171
            hfov: 55
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
```
