### ISSUE TITLE
Adding a localization_sensor

### ISSUE THREAD

**Issue by alre5639** [facebookresearch/habitat-lab#1707]
I would like to update the agent configuration in the [quickstart](https://aihabitat.org/docs/habitat-lab/quickstart.html) example to provide the location of the agent. I believe I should be able to do this by adding the `localization_sensor`  to the `pointnav_habitat_test.yaml` as shown below, however I get a `AttributeError: 'HabitatSim' object has no attribute 'get_agent_data'` result.  I am guessing this has something to do with the way the agent is defined in this configuration. How would I update the config to add this sensor? 

```
# @package _global_

defaults:
  - pointnav_base
  - /habitat/dataset/pointnav: habitat_test
  - /habitat/task/lab_sensors: localization_sensor #added this to get agent pose
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
```

Update: I should add that I can get the heading of the agent but updating `pointnav.yaml` by adding a `compass_sensor` lab sensor. however when I try to add a `localization_sensor` I get the above error
