### ISSUE TITLE
GL::Context: cannot retrieve OpenGL version: GL::Renderer::Error::InvalidVal

### ISSUE THREAD

**Issue by linyx700** [facebookresearch/habitat-lab#2104]
(habitat)` lyx@lyxHP:~/habitat$ python habitat-sim/examples/example.py
sim_cfg.physics_config_file = data/default.physics_config.json
GL::Context: cannot retrieve OpenGL version: GL::Renderer::Error::InvalidValue

is there anything wrong about the nvidia driver?
![截图 2024-11-06 21-58-25](https://github.com/user-attachments/assets/89d8c6b0-61c2-4a3c-a04a-e51caeb8cf1d)

**Comment by lasuomela** [comment]
Hi,

Did you manage to fix this? Running into the same issue.

**Comment by chuangguo** [comment]
The same issue, how did you solve it?

**Comment by yaioqin** [comment]
I downgraded the version of Habitat to 0.2.5, and the error is gone.

**Comment by ghubnerr** [comment]
> I downgraded the version of Habitat to 0.2.5, and the error is gone.

This worked or me -- although a little unideal to downgrade from Habitat 3. If anyone is able to fix this without the downgrade option, please let us know.

**Comment by Lazy-boy193** [comment]
> For me, the issue was caused by building habitat-sim from scratch in a conda environment with torchvision installed.
> 
> By default, conda might install build versions of torchvision dependencies (opencv, ffmpeg, libva) that install libgl and libegl from conda-forge into the environment. These seem to cause a driver conflict for habitat.
> 
> Installing these versions/builds solved the issue for me: ![IMG_5623](https://github.com/user-attachments/assets/7c82f938-945c-447e-8b73-27528cc92466)

How to find these packages and install them? I couldn't find a specific version in the conda installation. Furthermore, reducing the habitat to 0.2.5 cannot solve this problem: GL::Context: cannot retrieve OpenGL version: GL::Renderer::Error::InvalidValue

**Comment by lasuomela** [comment]
> > For me, the issue was caused by building habitat-sim from scratch in a conda environment with torchvision installed.
> > By default, conda might install build versions of torchvision dependencies (opencv, ffmpeg, libva) that install libgl and libegl from conda-forge into the environment. These seem to cause a driver conflict for habitat.
> > Installing these versions/builds solved the issue for me: ![IMG_5623](https://github.com/user-attachments/assets/7c82f938-945c-447e-8b73-27528cc92466)
> 
> How to find these packages and install them? I couldn't find a specific version in the conda installation. Furthermore, reducing the habitat to 0.2.5 cannot solve this problem: GL::Context: cannot retrieve OpenGL version: GL::Renderer::Error::InvalidValue

Hello,

My example image was from the conda environment.yml file. Below is my complete environment for reference. You might need to change the specific build of libva to fit your platform, but it has to be one that does not depend on libgl, libegl, or libglvnd.

```yaml
name: habitat_py310
channels:
  - pytorch
  - nvidia
  - huggingface
  - aihabitat
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - cmake
  - pytorch==2.4.0
  - torchvision
  - pytorch-cuda=12.4
  - ffmpeg=7.1.0
  - opencv[build=headless*] # Avoid installing libgl, libegl, libglvnd which break habitat-sim
  - libva[build=hb711507_0] # Avoid installing libgl, libegl, libglvnd
  - scipy
  - quaternion
  - numpy>=1.20.0,<1.24.0
  - numba
  - attrs
  - imageio
  - git
  - jsonpickle
  - pip
```
