### ISSUE TITLE
Observation transformation registry for Habitat baselines to provide input cropping, resizing, etc.

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-lab#367]
## 🚀 Feature

Observation transformation registry for Habitat baselines to provide input cropping, resizing, etc.

## Motivation
To make training pipeline agnostic to observation resolution or experiment with grayscale observations instead of RGB that would be great to have a list of supported transformations.

Reference [Resize and crop PR](https://github.com/facebookresearch/habitat-api/pull/365/).

## Pitch
1. Implement Transformations registry [here](https://github.com/facebookresearch/habitat-api/blob/master/habitat_baselines/common/baseline_registry.py).
2. Add nodes to [the habitat baselines config](url):
```
OBSERVATION_TRANSFORMATIONS: ["RESIZE", "CENTER_CROP", "GRAYSCALE"]
TRANSFORMATIONS:
    RESIZE:
        WIDTH: 640
        HEIGHT: 480
   CROP:
        WIDTH: 250
        HEIGHT: 250        
```

3. Add a call of the transformations chain to training and evaluation general code.
4. Transformations will change Observations space for models and should be addressed in the code.

## Alternative way
Same transformation can be implemented in Models hierarchy.
