### ISSUE TITLE
Objectnav datasets use `misc` category

### ISSUE THREAD

**Issue by smorad** [facebookresearch/habitat-lab#581]
## 🐛 Bug

The episodes generated for the mp3d `objectnav` task include the `misc (40)` [item category](https://github.com/niessner/Matterport/blob/master/metadata/mpcat40.tsv). This likely hinders agent training, as `misc` is to vague for even a human to understand. Current/future datasets would probably benefit from exclusion of `misc (40)` semantic targets, as well as: `objects (39)`, `unlabeled (41)`, `void (0)`, `wall (1)`, `floor(2)`.

## Steps to Reproduce

cfg:
```
DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val_mini
  DATA_PATH: "/root/habitat-lab/data/datasets/objectnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "/root/habitat-lab/data/scene_datasets/"
```
code:
```
scene = self._env.sim.semantic_annotations()
label_to_str_cat = {
                int(obj.id.split("_")[-1]): obj.category.name()
                for obj in scene.objects
            }
print(label_to_str_cat[obs['objectgoal'][0]])

>>> "misc"
```

Please note that without a minimal working example to reproduce the bug, we may not be able to help you. 

## Expected behavior

Semantic targets should not be too common/vague
