### ISSUE TITLE
Incorrect Distance_to_goal metric in ObjectNav task 

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/habitat-lab#889]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.1

Habitat-Sim: v0.2.1

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/ yes

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/ yes

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

I just build an ObjectGoal Env with Matterport3D semantic V0.1 and want to directly obtain some metrics from the environment to evaluate the performance of the agent. So I follow the instructions by setting the habitat config:
```
TASK: 
    TYPE: ObjectNav-v1 
    POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
    SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR'] MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL'] 
    SUCCESS: 
        SUCCESS_DISTANCE: 0.2
```

Then I obtain the distance_to_goal, which I think is the geodesic distance to the nearest goal, by:
```
self._env.get_metrics()["distance_to_goal"]
```

However, the result is quite large while the agent is close to one of the target goals (And I believe the RGB image proves the distance to the goal should be small). It seems like it still points to a far-away goal.
```
metrics {'distance_to_goal': 17.821653366088867, 'success': 0.0, 'spl': 0.0, 'softspl': 0.27454757027106463}
```
![image](https://user-images.githubusercontent.com/54199992/174252652-76b129da-a2b6-4352-b080-c6df46474950.png)

BTW, the metric of starting point is:
```
metrics {'distance_to_goal': 26.245790481567383, 'success': 0.0, 'spl': 0.0, 'softspl': 0.0}
```

I do not know whether it is purposely designed as the distance to goal in ObjectNav.  I hope my question is clear, and really appreciate any help.
