### ISSUE TITLE
TASK.SUCCESS.SUCCESS_DISTANCE v.s. TASK.SUCCESS_DISTANCE

### ISSUE THREAD

**Issue by sagadre** [facebookresearch/habitat-lab#893]
## ❓ Questions and Help

Based on the [habitat challenge 2022 object nav page](https://aihabitat.org/challenge/2022/), seems like the success distance should be 1.0m.

Looking at the default config I see the following:

```
TASK:
    SUCCESS:
        SUCCESS_DISTANCE: 0.1
        TYPE: Success
    SUCCESS_DISTANCE: 1.0
```

Just want to make sure that `TASK.SUCCESS_DISTANCE` is being used and not `TASK.SUCCESS.SUCCESS_DISTANCE` especially in light of this [PR](https://github.com/facebookresearch/habitat-lab/pull/784) suggesting `TASK.SUCCESS_DISTANCE` is supposed to be deprecated.

Tried digging around the code, but am not familiar with all the abstractions, so I decided to ask😄 

Thanks!

edit:
After playing around a bit, it does seem like `TASK.SUCCESS.SUCCESS_DISTANCE` is being used.
Does this mean that the success distance is 10.0cm and not 1.0m?
